Starknet foundry unit testing
carbonable-labs/cairo-erc-7498 pull request #9
Opened 2024-04-15 20:09 UTC by aagbotemi

This is the implementation of Starknet foundry unit testing using snforge

2024-04-16 10:15 UTC, tekkac commented
run `scarb fmt` on the code :)

2024-04-16 11:35 UTC, aagbotemi commented
I ran `scarb fmt` and `scarb build` on the code, and it was successful.

2024-04-24 13:50 UTC, tekkac requested changes
Thanks for your patience on the review.
Some additional rework is needed.
- mint test on the token aren't needed, what we'd like to unit test is the EIP7498 methods.
- some approvals aren't needed.
- most post method call checks are missing. <-- We want to check that the logic of the redemption is working here.
 - boundary checks are missing. <-- What happens when no token are left to redeem, etc.

Please try to not reuse code and import test methods you need if they exist.

Hope this is helpful.

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +use core::clone::Clone;
We should avoid cloning

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +use core::traits::TryInto;
I think this one is importent automatically in the prelude

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    calldata.append_serde(test_address());
Could you explain the use of `test_address()` in this context?

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +fn setup() -> (
Could this be imported from the other existing test file?

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +            recipient: BURN_ADDRESS()
Why BURN_ADDRESS here?

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +fn supports_interface() {
This test is already in the other test file I believe.

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    redeem_token.set_approval_for_all(redeem_contract_address, true);
Who is calling set_approval_for_all?
Might need a prank from a user here.

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    redeem_token.mint(OWNER(), TOKEN_ID);
Some checks on the minted token might be missing here.

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +#[should_panic()]
An expected panic message is missing here

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +#[should_panic()]
should catch the exact error message here

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    offer_array.append(offer);
```suggestion
    let mut offer_array = array![offer];
```

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    let timestamp: u32 = get_block_timestamp().try_into().unwrap();
I think timestamps should be u64, might need a change in the lib.

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    redeem_token.set_approval_for_all(redeem_contract_address, true);
You don't need approval here

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    redeem_token.mint(test_address(), TOKEN_ID);
mint_redemption already mints a NFT...

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +    receive_token.mint_redemption(CAMPAIGN_ID, test_address(), offer, consideration.span());
checks post mint missing

2024-04-24 13:50 UTC, tekkac commented on tests/erc7498_unit_test.cairo
> +#[should_panic()]
error missing

2024-04-25 11:21 UTC, aagbotemi commented on tests/erc7498_unit_test.cairo
> +            recipient: BURN_ADDRESS()
The recipient can actually be any address, meanwhile i have updated the recipient address.

2024-05-12 12:28 UTC, aagbotemi commented on tests/erc7498_unit_test.cairo
> +    calldata.append_serde(test_address());
it has been updated

2024-05-12 12:28 UTC, aagbotemi commented on tests/erc7498_unit_test.cairo
> +use core::clone::Clone;
Alright

2024-05-21 05:59 UTC, aagbotemi commented
Hi @tekkac, I've done the unit testing and resolved the issues you raised.

2024-06-24 16:46 UTC, tekkac commented
I'm closing this one as it has been superseded by the current Seaport issues.
Checks after executing the methods are still missing and it's not mergable so I'll close the PR.
If you're still interested in contributing, you could check with the contributors on the current Seaport issues if they want to split and pick up some of their work.

2024-06-24 16:46 UTC, closed without merging